CARDS = [
    {
        "title": "Личные местоимения",
        "entries": [
            {"num": 1, "word": "我", "pinyin": "wǒ", "translation": "я",
             "example": "我学汉语。", "example_pinyin": "Wǒ xué Hànyǔ.", "example_ru": "Я учу китайский язык."},
            {"num": 2, "word": "你", "pinyin": "nǐ", "translation": "ты",
             "example": "你好吗？", "example_pinyin": "Nǐ hǎo ma?", "example_ru": "Как ты?"},
            {"num": 3, "word": "他", "pinyin": "tā", "translation": "он",
             "example": "他是老师。", "example_pinyin": "Tā shì lǎoshī.", "example_ru": "Он — учитель."},
            {"num": 4, "word": "她", "pinyin": "tā", "translation": "она",
             "example": "她是学生。", "example_pinyin": "Tā shì xuésheng.", "example_ru": "Она — студентка."},
            {"num": 5, "word": "我们", "pinyin": "wǒmen", "translation": "мы",
             "example": "我们学习汉语。", "example_pinyin": "Wǒmen xuéxí Hànyǔ.", "example_ru": "Мы учим китайский."},
            {"num": 6, "word": "你们", "pinyin": "nǐmen", "translation": "вы",
             "example": "你们忙吗？", "example_pinyin": "Nǐmen máng ma?", "example_ru": "Вы заняты?"},
            {"num": 7, "word": "他们", "pinyin": "tāmen", "translation": "они",
             "example": "他们是朋友。", "example_pinyin": "Tāmen shì péngyou.", "example_ru": "Они — друзья."},
            {"num": 8, "word": "这", "pinyin": "zhè", "translation": "это (здесь)",
             "example": "这是书。", "example_pinyin": "Zhè shì shū.", "example_ru": "Это — книга."},
            {"num": 9, "word": "那", "pinyin": "nà", "translation": "то (туда)",
             "example": "那是学校。", "example_pinyin": "Nà shì xuéxiào.", "example_ru": "То — школа."},
            {"num": 10, "word": "谁", "pinyin": "shéi", "translation": "кто",
             "example": "他是谁？", "example_pinyin": "Tā shì shéi?", "example_ru": "Кто он?"}
        ]
    },
    {
        "title": "Семья",
        "entries": [
            {"num": 1, "word": "人", "pinyin": "rén", "translation": "человек",
             "example": "这里有很多人。", "example_pinyin": "Zhèlǐ yǒu hěn duō rén.",
             "example_ru": "Здесь много людей."},
            {"num": 2, "word": "爸爸", "pinyin": "bàba", "translation": "папа",
             "example": "我爸爸在家。", "example_pinyin": "Wǒ bàba zài jiā.", "example_ru": "Мой папа дома."},
            {"num": 3, "word": "妈妈", "pinyin": "māma", "translation": "мама",
             "example": "我妈妈很好。", "example_pinyin": "Wǒ māma hěn hǎo.", "example_ru": "Моя мама очень хорошая."},
            {"num": 4, "word": "儿子", "pinyin": "érzi", "translation": "сын",
             "example": "他有一个儿子。", "example_pinyin": "Tā yǒu yí gè érzi.", "example_ru": "У него есть сын."},
            {"num": 5, "word": "女儿", "pinyin": "nǚ'ér", "translation": "дочь",
             "example": "他有一个女儿。", "example_pinyin": "Tā yǒu yí gè nǚ'ér.", "example_ru": "У него есть дочь."},
            {"num": 6, "word": "家", "pinyin": "jiā", "translation": "дом; семья",
             "example": "我家很温暖。", "example_pinyin": "Wǒ jiā hěn wēnnuǎn.", "example_ru": "В моём доме тепло."},
            {"num": 7, "word": "朋友", "pinyin": "péngyou", "translation": "друг",
             "example": "他是我的朋友。", "example_pinyin": "Tā shì wǒ de péngyou.", "example_ru": "Он мой друг."},
            {"num": 8, "word": "老师", "pinyin": "lǎoshī", "translation": "учитель",
             "example": "她是我的老师。", "example_pinyin": "Tā shì wǒ de lǎoshī.",
             "example_ru": "Она моя учительница."},
            {"num": 9, "word": "学生", "pinyin": "xuésheng", "translation": "студент",
             "example": "他是学生。", "example_pinyin": "Tā shì xuésheng.", "example_ru": "Он студент."},
            {"num": 10, "word": "名字", "pinyin": "míngzi", "translation": "имя",
             "example": "你叫什么名字？", "example_pinyin": "Nǐ jiào shénme míngzi?", "example_ru": "Как тебя зовут?"}
        ]
    },
    {
        "title": "Числа",
        "entries": [
            {"num": 1, "word": "零", "pinyin": "líng", "translation": "ноль",
             "example": "零下五度。", "example_pinyin": "Líng xià wǔ dù.", "example_ru": "Пять градусов ниже нуля."},
            {"num": 2, "word": "一", "pinyin": "yī", "translation": "один",
             "example": "我有一只猫。", "example_pinyin": "Wǒ yǒu yì zhī māo.", "example_ru": "У меня одна кошка."},
            {"num": 3, "word": "二", "pinyin": "èr", "translation": "два",
             "example": "我有二只猫。", "example_pinyin": "Wǒ yǒu èr zhī māo.", "example_ru": "У меня две кошки."},
            {"num": 4, "word": "三", "pinyin": "sān", "translation": "три",
             "example": "我有三个朋友。", "example_pinyin": "Wǒ yǒu sān gè péngyou.", "example_ru": "У меня три друга."},
            {"num": 5, "word": "四", "pinyin": "sì", "translation": "четыре",
             "example": "他有四本书。", "example_pinyin": "Tā yǒu sì běn shū.", "example_ru": "У него четыре книги."},
            {"num": 6, "word": "五", "pinyin": "wǔ", "translation": "пять",
             "example": "我有五个苹果。", "example_pinyin": "Wǒ yǒu wǔ gè píngguǒ.", "example_ru": "У меня пять яблок."},
            {"num": 7, "word": "六", "pinyin": "liù", "translation": "шесть",
             "example": "我六岁。", "example_pinyin": "Wǒ liù suì.", "example_ru": "Мне шесть лет."},
            {"num": 8, "word": "七", "pinyin": "qī", "translation": "семь",
             "example": "我有七本书。", "example_pinyin": "Wǒ yǒu qī běn shū.", "example_ru": "У меня семь книг."},
            {"num": 9, "word": "八", "pinyin": "bā", "translation": "восемь",
             "example": "我有八本书。", "example_pinyin": "Wǒ yǒu bā běn shū.", "example_ru": "У меня восемь книг."},
            {"num": 10, "word": "九", "pinyin": "jiǔ", "translation": "девять",
             "example": "我九岁。", "example_pinyin": "Wǒ jiǔ suì.", "example_ru": "Мне девять лет."}
        ]
    },
    {
        "title": "Время",
        "entries": [
            {"num": 1, "word": "今天", "pinyin": "jīntiān", "translation": "сегодня",
             "example": "今天你忙吗？", "example_pinyin": "Jīntiān nǐ máng ma?", "example_ru": "Ты сегодня занят?"},
            {"num": 2, "word": "明天", "pinyin": "míngtiān", "translation": "завтра",
             "example": "明天见！", "example_pinyin": "Míngtiān jiàn!", "example_ru": "Увидимся завтра!"},
            {"num": 3, "word": "昨天", "pinyin": "zuótiān", "translation": "вчера",
             "example": "我昨天去了商店。", "example_pinyin": "Wǒ zuótiān qù le shāngdiàn.",
             "example_ru": "Вчера я ходил в магазин."},
            {"num": 4, "word": "年", "pinyin": "nián", "translation": "год",
             "example": "今年是哪年？", "example_pinyin": "Jīnnián shì nǎ nián?", "example_ru": "Какой сейчас год?"},
            {"num": 5, "word": "月", "pinyin": "yuè", "translation": "месяц",
             "example": "这个月很忙。", "example_pinyin": "Zhè ge yuè hěn máng.",
             "example_ru": "В этом месяце много дел."},
            {"num": 6, "word": "日", "pinyin": "rì", "translation": "день, дата",
             "example": "今天是三月一日。", "example_pinyin": "Jīntiān shì sān yuè yī rì.",
             "example_ru": "Сегодня первое марта."},
            {"num": 7, "word": "星期", "pinyin": "xīngqī", "translation": "неделя",
             "example": "今天星期三。", "example_pinyin": "Jīntiān xīngqī sān.", "example_ru": "Сегодня среда."},
            {"num": 8, "word": "时候", "pinyin": "shíhou", "translation": "время; момент",
             "example": "吃饭的时候他来了。", "example_pinyin": "Chīfàn de shíhou tā lái le.",
             "example_ru": "Когда ели, он пришёл."},
            {"num": 9, "word": "现在", "pinyin": "xiànzài", "translation": "сейчас",
             "example": "我现在很忙。", "example_pinyin": "Wǒ xiànzài hěn máng.", "example_ru": "Я сейчас очень занят."},
            {"num": 10, "word": "点", "pinyin": "diǎn", "translation": "час; точка",
             "example": "现在两点。", "example_pinyin": "Xiànzài liǎng diǎn.", "example_ru": "Сейчас два часа."}
        ]
    },
    {
        "title": "Глаголы действия",
        "entries": [
            {"num": 1, "word": "是", "pinyin": "shì", "translation": "быть",
             "example": "他是学生。", "example_pinyin": "Tā shì xuésheng.", "example_ru": "Он студент."},
            {"num": 2, "word": "有", "pinyin": "yǒu", "translation": "иметь; есть",
             "example": "我有三本书。", "example_pinyin": "Wǒ yǒu sān běn shū.", "example_ru": "У меня есть три книги."},
            {"num": 3, "word": "去", "pinyin": "qù", "translation": "идти; ехать",
             "example": "我去学校。", "example_pinyin": "Wǒ qù xuéxiào.", "example_ru": "Я иду в школу."},
            {"num": 4, "word": "来", "pinyin": "lái", "translation": "приходить",
             "example": "请他来。", "example_pinyin": "Qǐng tā lái.", "example_ru": "Попроси его прийти."},
            {"num": 5, "word": "看", "pinyin": "kàn", "translation": "смотреть; читать",
             "example": "我看电影。", "example_pinyin": "Wǒ kàn diànyǐng.", "example_ru": "Я смотрю фильм."},
            {"num": 6, "word": "听", "pinyin": "tīng", "translation": "слушать",
             "example": "我在听音乐。", "example_pinyin": "Wǒ zài tīng yīnyuè.", "example_ru": "Я слушаю музыку."},
            {"num": 7, "word": "说", "pinyin": "shuō", "translation": "говорить",
             "example": "他说汉语。", "example_pinyin": "Tā shuō Hànyǔ.", "example_ru": "Он говорит по-китайски."},
            {"num": 8, "word": "学", "pinyin": "xué", "translation": "учиться",
             "example": "我们学习汉语。", "example_pinyin": "Wǒmen xuéxí Hànyǔ.", "example_ru": "Мы учим китайский."},
            {"num": 9, "word": "吃", "pinyin": "chī", "translation": "есть",
             "example": "我吃苹果。", "example_pinyin": "Wǒ chī píngguǒ.", "example_ru": "Я ем яблоко."},
            {"num": 10, "word": "喝", "pinyin": "hē", "translation": "пить",
             "example": "我喝茶。", "example_pinyin": "Wǒ hē chá.", "example_ru": "Я пью чай."}
        ]
    },
    {
        "title": "Еда и напитки",
        "entries": [
            {"num": 1, "word": "水", "pinyin": "shuǐ", "translation": "вода",
             "example": "我喝水。", "example_pinyin": "Wǒ hē shuǐ.", "example_ru": "Я пью воду."},
            {"num": 2, "word": "茶", "pinyin": "chá", "translation": "чай",
             "example": "我喜欢喝茶。", "example_pinyin": "Wǒ xǐhuan hē chá.", "example_ru": "Я люблю пить чай."},
            {"num": 3, "word": "咖啡", "pinyin": "kāfēi", "translation": "кофе",
             "example": "我喝咖啡。", "example_pinyin": "Wǒ hē kāfēi.", "example_ru": "Я пью кофе."},
            {"num": 4, "word": "米饭", "pinyin": "mǐfàn", "translation": "варёный рис",
             "example": "我吃米饭。", "example_pinyin": "Wǒ chī mǐfàn.", "example_ru": "Я ем рис."},
            {"num": 5, "word": "菜", "pinyin": "cài", "translation": "блюдо; овощи",
             "example": "我喜欢吃菜。", "example_pinyin": "Wǒ xǐhuan chī cài.",
             "example_ru": "Я люблю есть овощи/блюда."},
            {"num": 6, "word": "苹果", "pinyin": "píngguǒ", "translation": "яблоко",
             "example": "我吃苹果。", "example_pinyin": "Wǒ chī píngguǒ.", "example_ru": "Я ем яблоко."},
            {"num": 7, "word": "喜欢", "pinyin": "xǐhuan", "translation": "нравиться",
             "example": "我喜欢这本书。", "example_pinyin": "Wǒ xǐhuan zhè běn shū.",
             "example_ru": "Мне нравится эта книга."},
            {"num": 8, "word": "买", "pinyin": "mǎi", "translation": "покупать",
             "example": "我想买这个。", "example_pinyin": "Wǒ xiǎng mǎi zhè ge.", "example_ru": "Я хочу купить это."},
            {"num": 9, "word": "多少", "pinyin": "duōshao", "translation": "сколько (стоит)",
             "example": "这个多少钱？", "example_pinyin": "Zhè ge duōshao qián?", "example_ru": "Сколько это стоит?"},
            {"num": 10, "word": "钱", "pinyin": "qián", "translation": "деньги",
             "example": "我没有钱。", "example_pinyin": "Wǒ méi yǒu qián.", "example_ru": "У меня нет денег."}
        ]
    },
    {
        "title": "Место / локация",
        "entries": [
            {"num": 1, "word": "在", "pinyin": "zài", "translation": "находиться; в",
             "example": "他在学校。", "example_pinyin": "Tā zài xuéxiào.", "example_ru": "Он в школе."},
            {"num": 2, "word": "这儿", "pinyin": "zhèr", "translation": "здесь",
             "example": "你在这儿吗？", "example_pinyin": "Nǐ zài zhèr ma?", "example_ru": "Ты здесь?"},
            {"num": 3, "word": "那儿", "pinyin": "nàr", "translation": "там",
             "example": "他在那儿。", "example_pinyin": "Tā zài nàr.", "example_ru": "Он там."},
            {"num": 4, "word": "学校", "pinyin": "xuéxiào", "translation": "школа",
             "example": "我去学校。", "example_pinyin": "Wǒ qù xuéxiào.", "example_ru": "Я иду в школу."},
            {"num": 5, "word": "中国", "pinyin": "Zhōngguó", "translation": "Китай",
             "example": "我爱中国。", "example_pinyin": "Wǒ ài Zhōngguó.", "example_ru": "Я люблю Китай."},
            {"num": 6, "word": "家", "pinyin": "jiā", "translation": "дом",
             "example": "我回家。", "example_pinyin": "Wǒ huí jiā.", "example_ru": "Я возвращаюсь домой."},
            {"num": 7, "word": "店", "pinyin": "diàn", "translation": "магазин",
             "example": "我去店里。", "example_pinyin": "Wǒ qù diàn lǐ.", "example_ru": "Я иду в магазин."},
            {"num": 8, "word": "医院", "pinyin": "yīyuàn", "translation": "больница",
             "example": "他去医院。", "example_pinyin": "Tā qù yīyuàn.", "example_ru": "Он идёт в больницу."},
            {"num": 9, "word": "哪", "pinyin": "nǎ", "translation": "где; какой",
             "example": "你去哪儿？", "example_pinyin": "Nǐ qù nǎr?", "example_ru": "Куда ты идёшь?"},
            {"num": 10, "word": "里", "pinyin": "lǐ", "translation": "внутри",
             "example": "书在包里。", "example_pinyin": "Shū zài bāo lǐ.", "example_ru": "Книга в сумке."}
        ]
    },
    {
        "title": "Вопросительные слова",
        "entries": [
            {"num": 1, "word": "什么", "pinyin": "shénme", "translation": "что",
             "example": "这是什么？", "example_pinyin": "Zhè shì shénme?", "example_ru": "Что это?"},
            {"num": 2, "word": "谁", "pinyin": "shéi", "translation": "кто",
             "example": "谁来了？", "example_pinyin": "Shéi lái le?", "example_ru": "Кто пришёл?"},
            {"num": 3, "word": "哪", "pinyin": "nǎ", "translation": "какой; где",
             "example": "哪儿是厕所？", "example_pinyin": "Nǎr shì cèsuǒ?", "example_ru": "Где туалет?"},
            {"num": 4, "word": "几", "pinyin": "jǐ", "translation": "сколько (мал.)",
             "example": "你家有几口人？", "example_pinyin": "Nǐ jiā yǒu jǐ kǒu rén?",
             "example_ru": "Сколько человек в твоей семье?"},
            {"num": 5, "word": "多少", "pinyin": "duōshao", "translation": "сколько (количество/стоимость)",
             "example": "这个多少钱？", "example_pinyin": "Zhè ge duōshao?", "example_ru": "Сколько это стоит?"},
            {"num": 6, "word": "吗", "pinyin": "ma", "translation": "вопросительная частица",
             "example": "你会说汉语吗？", "example_pinyin": "Nǐ huì shuō Hànyǔ ma?",
             "example_ru": "Ты говоришь по-китайски?"},
            {"num": 7, "word": "呢", "pinyin": "ne", "translation": "частица (вопрос)",
             "example": "你呢？", "example_pinyin": "Nǐ ne?", "example_ru": "А ты?"},
            {"num": 8, "word": "怎么", "pinyin": "zěnme", "translation": "как",
             "example": "这怎么用？", "example_pinyin": "Zhè zěnme yòng?", "example_ru": "Как это использовать?"},
            {"num": 9, "word": "为什么", "pinyin": "wèishénme", "translation": "почему",
             "example": "你为什么学习汉语？", "example_pinyin": "Nǐ wèishénme xuéxí Hànyǔ?",
             "example_ru": "Почему ты изучаешь китайский?"},
            {"num": 10, "word": "什么时候", "pinyin": "shénme shíhou", "translation": "когда",
             "example": "你什么时候去？", "example_pinyin": "Nǐ shénme shíhou qù?", "example_ru": "Когда ты пойдёшь?"}
        ]
    },
    {
        "title": "Прилагательные",
        "entries": [
            {"num": 1, "word": "大", "pinyin": "dà", "translation": "большой",
             "example": "这个房间很大。", "example_pinyin": "Zhè ge fángjiān hěn dà.",
             "example_ru": "Эта комната большая."},
            {"num": 2, "word": "小", "pinyin": "xiǎo", "translation": "маленький",
             "example": "这个很小。", "example_pinyin": "Zhè ge hěn xiǎo.", "example_ru": "Это очень маленькое."},
            {"num": 3, "word": "多", "pinyin": "duō", "translation": "много",
             "example": "这里人很多。", "example_pinyin": "Zhèlǐ rén hěn duō.", "example_ru": "Здесь много людей."},
            {"num": 4, "word": "少", "pinyin": "shǎo", "translation": "мало",
             "example": "时间很少。", "example_pinyin": "Shíjiān hěn shǎo.", "example_ru": "Мало времени."},
            {"num": 5, "word": "好", "pinyin": "hǎo", "translation": "хороший",
             "example": "这本书很好。", "example_pinyin": "Zhè běn shū hěn hǎo.",
             "example_ru": "Эта книга очень хорошая."},
            {"num": 6, "word": "坏", "pinyin": "huài", "translation": "плохой",
             "example": "这个菜不好吃，很坏。", "example_pinyin": "Zhè ge cài bù hǎochī, hěn huài.",
             "example_ru": "Это блюдо невкусное, очень плохое."},
            {"num": 7, "word": "热", "pinyin": "rè", "translation": "жарко; горячий",
             "example": "今天很热。", "example_pinyin": "Jīntiān hěn rè.", "example_ru": "Сегодня жарко."},
            {"num": 8, "word": "冷", "pinyin": "lěng", "translation": "холодно; холодный",
             "example": "外面很冷。", "example_pinyin": "Wàimiàn hěn lěng.", "example_ru": "На улице очень холодно."},
            {"num": 9, "word": "快", "pinyin": "kuài", "translation": "быстро",
             "example": "快走！", "example_pinyin": "Kuài zǒu!", "example_ru": "Иди быстрее!"},
            {"num": 10, "word": "慢", "pinyin": "màn", "translation": "медленно",
             "example": "别走得太慢。", "example_pinyin": "Bié zǒu de tài màn.",
             "example_ru": "Не ходи слишком медленно."}
        ]
    },
    {
        "title": "Частицы и служебные слова",
        "entries": [
            {"num": 1, "word": "的", "pinyin": "de", "translation": "служебная частица (притяж.)",
             "example": "这是我的书。", "example_pinyin": "Zhè shì wǒ de shū.", "example_ru": "Это моя книга."},
            {"num": 2, "word": "不", "pinyin": "bù", "translation": "не (отриц.)",
             "example": "我不去。", "example_pinyin": "Wǒ bù qù.", "example_ru": "Я не пойду."},
            {"num": 3, "word": "没", "pinyin": "méi", "translation": "не (прош.)",
             "example": "我昨天没来。", "example_pinyin": "Wǒ zuótiān méi lái.", "example_ru": "Вчера я не пришёл."},
            {"num": 4, "word": "很", "pinyin": "hěn", "translation": "очень",
             "example": "他很高兴。", "example_pinyin": "Tā hěn gāoxìng.", "example_ru": "Он очень рад."},
            {"num": 5, "word": "也", "pinyin": "yě", "translation": "тоже",
             "example": "我也喜欢。", "example_pinyin": "Wǒ yě xǐhuan.", "example_ru": "Мне тоже нравится."},
            {"num": 6, "word": "都", "pinyin": "dōu", "translation": "все; всё",
             "example": "他们都来了。", "example_pinyin": "Tāmen dōu lái le.", "example_ru": "Они все пришли."},
            {"num": 7, "word": "还", "pinyin": "hái", "translation": "ещё; всё ещё",
             "example": "他还在家。", "example_pinyin": "Tā hái zài jiā.", "example_ru": "Он ещё дома."},
            {"num": 8, "word": "就", "pinyin": "jiù", "translation": "как раз; сразу",
             "example": "我就去。", "example_pinyin": "Wǒ jiù qù.", "example_ru": "Я сразу пойду."},
            {"num": 9, "word": "吧", "pinyin": "ba", "translation": "частица (предположение/мягкость)",
             "example": "我们走吧。", "example_pinyin": "Wǒmen zǒu ba.", "example_ru": "Пойдём, ладно?"},
            {"num": 10, "word": "呢", "pinyin": "ne", "translation": "частица (вопрос: а...?)",
             "example": "你呢？", "example_pinyin": "Nǐ ne?", "example_ru": "А ты?"}
        ]
    },
    {
        "title": "Учёба / книги",
        "entries": [
            {"num": 1, "word": "汉语", "pinyin": "Hànyǔ", "translation": "китайский язык",
             "example": "我学汉语。", "example_pinyin": "Wǒ xué Hànyǔ.", "example_ru": "Я учу китайский."},
            {"num": 2, "word": "字", "pinyin": "zì", "translation": "иероглиф; буква",
             "example": "这个字怎么读？", "example_pinyin": "Zhè ge zì zěnme dú?",
             "example_ru": "Как читать этот иероглиф?"},
            {"num": 3, "word": "书", "pinyin": "shū", "translation": "книга",
             "example": "我有很多书。", "example_pinyin": "Wǒ yǒu hěn duō shū.", "example_ru": "У меня много книг."},
            {"num": 4, "word": "写", "pinyin": "xiě", "translation": "писать",
             "example": "请你写名字。", "example_pinyin": "Qǐng nǐ xiě míngzi.",
             "example_ru": "Пожалуйста, напиши имя."},
            {"num": 5, "word": "读", "pinyin": "dú", "translation": "читать",
             "example": "我在读书。", "example_pinyin": "Wǒ zài dú shū.", "example_ru": "Я читаю книгу."},
            {"num": 6, "word": "老师", "pinyin": "lǎoshī", "translation": "учитель",
             "example": "老师很友好。", "example_pinyin": "Lǎoshī hěn yǒuhǎo.", "example_ru": "Учитель очень добрый."},
            {"num": 7, "word": "学生", "pinyin": "xuésheng", "translation": "ученик; студент",
             "example": "我是学生。", "example_pinyin": "Wǒ shì xuésheng.", "example_ru": "Я студент."},
            {"num": 8, "word": "学习", "pinyin": "xuéxí", "translation": "учиться",
             "example": "我们学习汉语。", "example_pinyin": "Wǒmen xuéxí Hànyǔ.", "example_ru": "Мы учим китайский."},
            {"num": 9, "word": "考试", "pinyin": "kǎoshì", "translation": "экзамен",
             "example": "明天有考试。", "example_pinyin": "Míngtiān yǒu kǎoshì.", "example_ru": "Завтра экзамен."},
            {"num": 10, "word": "问题", "pinyin": "wèntí", "translation": "вопрос; проблема",
             "example": "你有问题吗？", "example_pinyin": "Nǐ yǒu wèntí ma?", "example_ru": "У тебя есть вопросы?"}
        ]
    },
    {
        "title": "Движение",
        "entries": [
            {"num": 1, "word": "走", "pinyin": "zǒu", "translation": "идти (пешком)",
             "example": "我们走吧。", "example_pinyin": "Wǒmen zǒu ba.", "example_ru": "Пойдём."},
            {"num": 2, "word": "跑", "pinyin": "pǎo", "translation": "бежать",
             "example": "他跑得很快。", "example_pinyin": "Tā pǎo de hěn kuài.", "example_ru": "Он бегает быстро."},
            {"num": 3, "word": "坐", "pinyin": "zuò", "translation": "сидеть; ехать (на трансп.)",
             "example": "我坐车去学校。", "example_pinyin": "Wǒ zuò chē qù xuéxiào.",
             "example_ru": "Я еду на машине в школу."},
            {"num": 4, "word": "站", "pinyin": "zhàn", "translation": "стоять",
             "example": "请在这里站。", "example_pinyin": "Qǐng zài zhèlǐ zhàn.",
             "example_ru": "Пожалуйста, встаньте здесь."},
            {"num": 5, "word": "进", "pinyin": "jìn", "translation": "входить",
             "example": "他进教室了。", "example_pinyin": "Tā jìn jiàoshì le.", "example_ru": "Он вошёл в класс."},
            {"num": 6, "word": "出", "pinyin": "chū", "translation": "выходить",
             "example": "他出去了。", "example_pinyin": "Tā chū qù le.", "example_ru": "Он вышел."},
            {"num": 7, "word": "回", "pinyin": "huí", "translation": "возвращаться",
             "example": "我回家了。", "example_pinyin": "Wǒ huí jiā le.", "example_ru": "Я вернулся домой."},
            {"num": 8, "word": "到", "pinyin": "dào", "translation": "прибывать; до",
             "example": "他到了学校。", "example_pinyin": "Tā dào le xuéxiào.", "example_ru": "Он пришёл в школу."},
            {"num": 9, "word": "上", "pinyin": "shàng", "translation": "вверх; прошлый",
             "example": "上星期我很忙。", "example_pinyin": "Shàng xīngqī wǒ hěn máng.",
             "example_ru": "На прошлой неделе я был занят."},
            {"num": 10, "word": "下", "pinyin": "xià", "translation": "вниз; следующий",
             "example": "请坐下。", "example_pinyin": "Qǐng zuò xià.", "example_ru": "Пожалуйста, садитесь."}
        ]
    },
    {
        "title": "Покупки",
        "entries": [
            {"num": 1, "word": "买", "pinyin": "mǎi", "translation": "покупать",
             "example": "我想买这个。", "example_pinyin": "Wǒ xiǎng mǎi zhè ge.", "example_ru": "Я хочу купить это."},
            {"num": 2, "word": "卖", "pinyin": "mài", "translation": "продавать",
             "example": "他在卖水果。", "example_pinyin": "Tā zài mài shuǐguǒ.", "example_ru": "Он продаёт фрукты."},
            {"num": 3, "word": "东西", "pinyin": "dōngxi", "translation": "вещи",
             "example": "我买东西。", "example_pinyin": "Wǒ mǎi dōngxi.", "example_ru": "Я покупаю вещи."},
            {"num": 4, "word": "钱", "pinyin": "qián", "translation": "деньги",
             "example": "这个多少钱？", "example_pinyin": "Zhè ge duōshao qián?", "example_ru": "Сколько это стоит?"},
            {"num": 5, "word": "贵", "pinyin": "guì", "translation": "дорогой",
             "example": "这个东西很贵。", "example_pinyin": "Zhè ge dōngxi hěn guì.", "example_ru": "Эта вещь дорогая."},
            {"num": 6, "word": "便宜", "pinyin": "piányi", "translation": "дешёвый",
             "example": "这个很便宜。", "example_pinyin": "Zhè ge hěn piányi.", "example_ru": "Это очень дешево."},
            {"num": 7, "word": "商店", "pinyin": "shāngdiàn", "translation": "магазин",
             "example": "我去商店买东西。", "example_pinyin": "Wǒ qù shāngdiàn mǎi dōngxi.",
             "example_ru": "Я иду в магазин покупать вещи."},
            {"num": 8, "word": "多少", "pinyin": "duōshao", "translation": "сколько",
             "example": "这个多少钱？", "example_pinyin": "Zhè ge duōshao?", "example_ru": "Сколько это стоит?"},
            {"num": 9, "word": "块", "pinyin": "kuài", "translation": "сч.слово (юань/кусок)",
             "example": "这个十块钱。", "example_pinyin": "Zhè ge shí kuài qián.",
             "example_ru": "Это стоит десять юаней."},
            {"num": 10, "word": "要", "pinyin": "yào", "translation": "хотеть; нужно",
             "example": "我要这个。", "example_pinyin": "Wǒ yào zhè ge.", "example_ru": "Я хочу это."}
        ]
    },
    {
        "title": "Здоровье",
        "entries": [
            {"num": 1, "word": "医生", "pinyin": "yīshēng", "translation": "врач",
             "example": "我去看医生。", "example_pinyin": "Wǒ qù kàn yīshēng.", "example_ru": "Я иду к врачу."},
            {"num": 2, "word": "医院", "pinyin": "yīyuàn", "translation": "больница",
             "example": "他在医院工作。", "example_pinyin": "Tā zài yīyuàn gōngzuò.",
             "example_ru": "Он работает в больнице."},
            {"num": 3, "word": "病", "pinyin": "bìng", "translation": "болезнь",
             "example": "我生病了。", "example_pinyin": "Wǒ shēngbìng le.", "example_ru": "Я заболел."},
            {"num": 4, "word": "药", "pinyin": "yào", "translation": "лекарство",
             "example": "医生给我药。", "example_pinyin": "Yīshēng gěi wǒ yào.",
             "example_ru": "Врач дал мне лекарство."},
            {"num": 5, "word": "疼", "pinyin": "téng", "translation": "болеть",
             "example": "我的头很疼。", "example_pinyin": "Wǒ de tóu hěn téng.",
             "example_ru": "У меня сильно болит голова."},
            {"num": 6, "word": "身体", "pinyin": "shēntǐ", "translation": "тело; здоровье",
             "example": "你身体好吗？", "example_pinyin": "Nǐ shēntǐ hǎo ma?", "example_ru": "Как твоё здоровье?"},
            {"num": 7, "word": "看病", "pinyin": "kànbìng", "translation": "ходить к врачу",
             "example": "他去看病了。", "example_pinyin": "Tā qù kànbìng le.", "example_ru": "Он пошёл к врачу."},
            {"num": 8, "word": "不舒服", "pinyin": "bù shūfu", "translation": "плохо (самочувствие)",
             "example": "我不舒服。", "example_pinyin": "Wǒ bù shūfu.", "example_ru": "Я плохо себя чувствую."},
            {"num": 9, "word": "休息", "pinyin": "xiūxi", "translation": "отдыхать",
             "example": "你要休息。", "example_pinyin": "Nǐ yào xiūxi.", "example_ru": "Тебе нужно отдохнуть."},
            {"num": 10, "word": "好", "pinyin": "hǎo", "translation": "хорошо",
             "example": "现在我好些了。", "example_pinyin": "Xiànzài wǒ hǎoxiē le.", "example_ru": "Сейчас мне лучше."}
        ]
    },
    {
        "title": "Разговорные фразы / приветствия",
        "entries": [
            {"num": 1, "word": "喂", "pinyin": "wèi", "translation": "алло; эй",
             "example": "喂，你好。", "example_pinyin": "Wèi, nǐ hǎo.", "example_ru": "Алло, привет."},
            {"num": 2, "word": "我", "pinyin": "wǒ", "translation": "я",
             "example": "我叫李明。", "example_pinyin": "Wǒ jiào Lǐ Míng.", "example_ru": "Меня зовут Ли Мин."},
            {"num": 3, "word": "我们", "pinyin": "wǒmen", "translation": "мы",
             "example": "我们是学生。", "example_pinyin": "Wǒmen shì xuésheng.", "example_ru": "Мы — студенты."},
            {"num": 4, "word": "五", "pinyin": "wǔ", "translation": "пять",
             "example": "我有五个苹果。", "example_pinyin": "Wǒ yǒu wǔ gè píngguǒ.", "example_ru": "У меня пять яблок."},
            {"num": 5, "word": "喜欢", "pinyin": "xǐhuan", "translation": "нравиться",
             "example": "我喜欢你。", "example_pinyin": "Wǒ xǐhuan nǐ.", "example_ru": "Ты мне нравишься."},
            {"num": 6, "word": "下", "pinyin": "xià", "translation": "вниз; следующий",
             "example": "请坐下。", "example_pinyin": "Qǐng zuò xià.", "example_ru": "Пожалуйста, садитесь."},
            {"num": 7, "word": "下午", "pinyin": "xiàwǔ", "translation": "после полудня",
             "example": "下午我去商店。", "example_pinyin": "Xiàwǔ wǒ qù shāngdiàn.",
             "example_ru": "Днём я иду в магазин."},
            {"num": 8, "word": "下雨", "pinyin": "xià yǔ", "translation": "идёт дождь",
             "example": "今天下雨了。", "example_pinyin": "Jīntiān xià yǔ le.", "example_ru": "Сегодня пошёл дождь."},
            {"num": 9, "word": "先生", "pinyin": "xiānsheng", "translation": "господин; мистер",
             "example": "李先生好。", "example_pinyin": "Lǐ xiānsheng hǎo.", "example_ru": "Здравствуйте, господин Ли."},
            {"num": 10, "word": "现在", "pinyin": "xiànzài", "translation": "сейчас",
             "example": "我现在很忙。", "example_pinyin": "Wǒ xiànzài hěn máng.", "example_ru": "Я сейчас очень занят."}
        ]
    },
    {
        "title": "Желания / маленькие слова",
        "entries": [
            {"num": 1, "word": "想", "pinyin": "xiǎng", "translation": "хотеть; думать",
             "example": "我想吃饭。", "example_pinyin": "Wǒ xiǎng chīfàn.", "example_ru": "Я хочу поесть."},
            {"num": 2, "word": "小", "pinyin": "xiǎo", "translation": "маленький",
             "example": "这个房间很小。", "example_pinyin": "Zhè ge fángjiān hěn xiǎo.",
             "example_ru": "Эта комната маленькая."},
            {"num": 3, "word": "小姐", "pinyin": "xiǎojiě", "translation": "мисс",
             "example": "小姐，你好。", "example_pinyin": "Xiǎojiě, nǐ hǎo.", "example_ru": "Здравствуйте, мисс."},
            {"num": 4, "word": "些", "pinyin": "xiē", "translation": "несколько",
             "example": "我有些问题。", "example_pinyin": "Wǒ yǒu xiē wèntí.",
             "example_ru": "У меня есть несколько вопросов."},
            {"num": 5, "word": "写", "pinyin": "xiě", "translation": "писать",
             "example": "请你写名字。", "example_pinyin": "Qǐng nǐ xiě míngzi.",
             "example_ru": "Пожалуйста, напиши имя."},
            {"num": 6, "word": "谢谢", "pinyin": "xièxie", "translation": "спасибо",
             "example": "谢谢你！", "example_pinyin": "Xièxie nǐ!", "example_ru": "Спасибо тебе!"},
            {"num": 7, "word": "星期", "pinyin": "xīngqī", "translation": "неделя",
             "example": "今天星期三。", "example_pinyin": "Jīntiān xīngqī sān.", "example_ru": "Сегодня среда."},
            {"num": 8, "word": "学生", "pinyin": "xuésheng", "translation": "студент",
             "example": "他是学生。", "example_pinyin": "Tā shì xuésheng.", "example_ru": "Он студент."},
            {"num": 9, "word": "学习", "pinyin": "xuéxí", "translation": "учиться",
             "example": "我们学习汉语。", "example_pinyin": "Wǒmen xuéxí Hànyǔ.", "example_ru": "Мы учим китайский."},
            {"num": 10, "word": "学校", "pinyin": "xuéxiào", "translation": "школа",
             "example": "我去学校。", "example_pinyin": "Wǒ qù xuéxiào.", "example_ru": "Я иду в школу."}
        ]
    },
    {
        "title": "Покупки / базовые существительные",
        "entries": [
            {"num": 1, "word": "一", "pinyin": "yī", "translation": "один",
             "example": "我有一只猫。", "example_pinyin": "Wǒ yǒu yī zhī māo.", "example_ru": "У меня одна кошка."},
            {"num": 2, "word": "衣服", "pinyin": "yīfu", "translation": "одежда",
             "example": "这件衣服很漂亮。", "example_pinyin": "Zhè jiàn yīfu hěn piàoliang.",
             "example_ru": "Эта одежда очень красивая."},
            {"num": 3, "word": "医生", "pinyin": "yīshēng", "translation": "врач",
             "example": "我去看医生。", "example_pinyin": "Wǒ qù kàn yīshēng.", "example_ru": "Я иду к врачу."},
            {"num": 4, "word": "医院", "pinyin": "yīyuàn", "translation": "больница",
             "example": "他在医院工作。", "example_pinyin": "Tā zài yīyuàn gōngzuò.",
             "example_ru": "Он работает в больнице."},
            {"num": 5, "word": "椅子", "pinyin": "yǐzi", "translation": "стул",
             "example": "请坐在椅子上。", "example_pinyin": "Qǐng zuò zài yǐzi shàng.",
             "example_ru": "Пожалуйста, сядь на стул."},
            {"num": 6, "word": "有", "pinyin": "yǒu", "translation": "иметь; есть",
             "example": "我有三本书。", "example_pinyin": "Wǒ yǒu sān běn shū.", "example_ru": "У меня есть три книги."},
            {"num": 7, "word": "月", "pinyin": "yuè", "translation": "месяц",
             "example": "这个月很忙。", "example_pinyin": "Zhè ge yuè hěn máng.",
             "example_ru": "В этом месяце много дел."},
            {"num": 8, "word": "在", "pinyin": "zài", "translation": "находиться; в",
             "example": "我在教室。", "example_pinyin": "Wǒ zài jiàoshì.", "example_ru": "Я в классе."},
            {"num": 9, "word": "再见", "pinyin": "zàijiàn", "translation": "до свидания",
             "example": "再见！", "example_pinyin": "Zàijiàn!", "example_ru": "До свидания!"},
            {"num": 10, "word": "怎么", "pinyin": "zěnme", "translation": "как",
             "example": "这怎么用？", "example_pinyin": "Zhè zěnme yòng?", "example_ru": "Как это использовать?"}
        ]
    },
    {
        "title": "Фразы / завершение",
        "entries": [
            {"num": 1, "word": "怎么样", "pinyin": "zěnmeyàng", "translation": "как (о состоянии)",
             "example": "你怎么样？", "example_pinyin": "Nǐ zěnmeyàng?", "example_ru": "Как ты? / Как дела?"},
            {"num": 2, "word": "这", "pinyin": "zhè", "translation": "это; этот",
             "example": "这是我的书。", "example_pinyin": "Zhè shì wǒ de shū.", "example_ru": "Это моя книга."},
            {"num": 3, "word": "中国", "pinyin": "Zhōngguó", "translation": "Китай",
             "example": "我爱中国。", "example_pinyin": "Wǒ ài Zhōngguó.", "example_ru": "Я люблю Китай."},
            {"num": 4, "word": "中午", "pinyin": "zhōngwǔ", "translation": "полдень",
             "example": "我中午吃饭。", "example_pinyin": "Wǒ zhōngwǔ chīfàn.", "example_ru": "Я обедаю в полдень."},
            {"num": 5, "word": "住", "pinyin": "zhù", "translation": "жить; проживать",
             "example": "我住在北京。", "example_pinyin": "Wǒ zhù zài Běijīng.", "example_ru": "Я живу в Пекине."},
            {"num": 6, "word": "桌子", "pinyin": "zhuōzi", "translation": "стол",
             "example": "桌子上有书。", "example_pinyin": "Zhuōzi shàng yǒu shū.", "example_ru": "На столе есть книга."},
            {"num": 7, "word": "字", "pinyin": "zì", "translation": "иероглиф; слово",
             "example": "这个字怎么读？", "example_pinyin": "Zhè ge zì zěnme dú?",
             "example_ru": "Как читается этот иероглиф?"},
            {"num": 8, "word": "昨天", "pinyin": "zuótiān", "translation": "вчера",
             "example": "我昨天去了商店。", "example_pinyin": "Wǒ zuótiān qù le shāngdiàn.",
             "example_ru": "Вчера я ходил в магазин."},
            {"num": 9, "word": "坐", "pinyin": "zuò", "translation": "сидеть; ехать (на трансп.)",
             "example": "我坐车去学校。", "example_pinyin": "Wǒ zuò chē qù xuéxiào.",
             "example_ru": "Я еду на машине в школу."},
            {"num": 10, "word": "做", "pinyin": "zuò", "translation": "делать",
             "example": "你在做什么？", "example_pinyin": "Nǐ zài zuò shénme?", "example_ru": "Что ты делаешь?"}
        ]
    }
]
WORDS = [
    {'id': 1, 'word': '爱', 'pinyin': 'ài', 'translation_ru': 'любить; любовь; любимый'},
    {'id': 2, 'word': '八', 'pinyin': 'bā', 'translation_ru': 'восемь; восьмой'},
    {'id': 3, 'word': '爸爸', 'pinyin': 'bàba', 'translation_ru': 'папа, тятя'},
    {'id': 4, 'word': '杯子', 'pinyin': 'bēizi', 'translation_ru': 'стакан; кружка; бокал; рюмка'},
    {'id': 5, 'word': '北京', 'pinyin': 'běijīng', 'translation_ru': 'Пекин'},
    {'id': 6, 'word': '本', 'pinyin': 'běn', 'translation_ru': 'счётное слово для растений'},
    {'id': 8, 'word': '不', 'pinyin': 'bù', 'translation_ru': 'отрицательная частица не'},
    {'id': 9, 'word': '菜', 'pinyin': 'cài', 'translation_ru': 'овощи; блюдо; пища; стол 种菜'},
    {'id': 10, 'word': '茶', 'pinyin': 'chá', 'translation_ru': 'чай 喝茶'},
    {'id': 11, 'word': '吃', 'pinyin': 'chī', 'translation_ru': 'есть, кушать'},
    {'id': 14, 'word': '大', 'pinyin': 'dà', 'translation_ru': 'большой; крупный; великий'},
    {'id': 15, 'word': '的', 'pinyin': 'de', 'translation_ru': 'суффикс прилагательного'},
    {'id': 16, 'word': '点', 'pinyin': 'diǎn', 'translation_ru': 'капля; немножко, чуточку; точка'},
    {'id': 17, 'word': '电脑', 'pinyin': 'diànnǎo', 'translation_ru': 'компьютер'},
    {'id': 18, 'word': '电视', 'pinyin': 'diànshì', 'translation_ru': 'телевизор'},
    {'id': 19, 'word': '电影', 'pinyin': 'diànyǐng', 'translation_ru': 'фильм; кино'},
    {'id': 20, 'word': '东', 'pinyin': 'dōng', 'translation_ru': 'восток'},
    {'id': 21, 'word': '都', 'pinyin': 'dōu', 'translation_ru': 'все; оба'},
    {'id': 22, 'word': '读', 'pinyin': 'dú', 'translation_ru': 'читать; учиться'},
    {'id': 23, 'word': '对不起', 'pinyin': 'duìbuqǐ', 'translation_ru': 'извините, прошу прощения'},
    {'id': 24, 'word': '多', 'pinyin': 'duō', 'translation_ru': 'много; более'},
    {'id': 25, 'word': '多少', 'pinyin': 'duōshao', 'translation_ru': 'сколько?'},
    {'id': 26, 'word': '儿子', 'pinyin': 'érzi', 'translation_ru': 'сын'},
    {'id': 27, 'word': '二', 'pinyin': 'èr', 'translation_ru': 'два; второй'},
    {'id': 28, 'word': '饭店', 'pinyin': 'fàndiàn', 'translation_ru': 'ресторан; гостиница'},
    {'id': 29, 'word': '飞机', 'pinyin': 'fēijī', 'translation_ru': 'самолёт'},
    {'id': 30, 'word': '分钟', 'pinyin': 'fēnzhōng', 'translation_ru': 'минута (единица времени)'},
    {'id': 31, 'word': '高兴', 'pinyin': 'gāoxìng', 'translation_ru': 'радостный; довольный'},
    {'id': 32, 'word': '个', 'pinyin': 'gè', 'translation_ru': 'универсальное счётное слово'},
    {'id': 33, 'word': '工作', 'pinyin': 'gōngzuò', 'translation_ru': 'работать; работа'},
    {'id': 34, 'word': '狗', 'pinyin': 'gǒu', 'translation_ru': 'собака'},
    {'id': 35, 'word': '汉语', 'pinyin': 'Hànyǔ', 'translation_ru': 'китайский язык'},
    {'id': 36, 'word': '好', 'pinyin': 'hǎo', 'translation_ru': 'хороший; хорошо'},
    {'id': 37, 'word': '号', 'pinyin': 'hào', 'translation_ru': 'номер; день месяца'},
    {'id': 38, 'word': '喝', 'pinyin': 'hē', 'translation_ru': 'пить'},
    {'id': 39, 'word': '和', 'pinyin': 'hé', 'translation_ru': 'и; с'},
    {'id': 40, 'word': '很', 'pinyin': 'hěn', 'translation_ru': 'очень'},
    {'id': 41, 'word': '后面', 'pinyin': 'hòumiàn', 'translation_ru': 'позади; сзади'},
    {'id': 42, 'word': '回', 'pinyin': 'huí', 'translation_ru': 'возвращаться'},
    {'id': 43, 'word': '会', 'pinyin': 'huì', 'translation_ru': 'уметь; быть в состоянии; собираться'},
    {'id': 44, 'word': '几', 'pinyin': 'jǐ', 'translation_ru': 'несколько; сколько (малое число)'},
    {'id': 45, 'word': '家', 'pinyin': 'jiā', 'translation_ru': 'дом; семья'},
    {'id': 46, 'word': '叫', 'pinyin': 'jiào', 'translation_ru': 'называться; кричать'},
    {'id': 47, 'word': '今天', 'pinyin': 'jīntiān', 'translation_ru': 'сегодня'},
    {'id': 48, 'word': '京', 'pinyin': 'jīng', 'translation_ru': 'столица (короткая форма Пекина)'},
    {'id': 49, 'word': '九', 'pinyin': 'jiǔ', 'translation_ru': 'девять'},
    {'id': 50, 'word': '开', 'pinyin': 'kāi', 'translation_ru': 'открывать; водить (машину)'},
    {'id': 51, 'word': '看', 'pinyin': 'kàn', 'translation_ru': 'смотреть; читать'},
    {'id': 52, 'word': '看见', 'pinyin': 'kànjiàn', 'translation_ru': 'увидеть; заметить'},
    {'id': 53, 'word': '块', 'pinyin': 'kuài', 'translation_ru': 'кусок; юань (разговорное)'},
    {'id': 54, 'word': '来', 'pinyin': 'lái', 'translation_ru': 'приходить; приехать'},
    {'id': 55, 'word': '老师', 'pinyin': 'lǎoshī', 'translation_ru': 'учитель'},
    {'id': 56, 'word': '了', 'pinyin': 'le', 'translation_ru': 'прошедшая частица / модификатор состояния'},
    {'id': 57, 'word': '冷', 'pinyin': 'lěng', 'translation_ru': 'холодный'},
    {'id': 58, 'word': '里', 'pinyin': 'lǐ', 'translation_ru': 'внутри; внутри чего-либо'},
    {'id': 59, 'word': '妈妈', 'pinyin': 'māma', 'translation_ru': 'мама'},
    {'id': 60, 'word': '吗', 'pinyin': 'ma', 'translation_ru': 'вопросительная частица'},
    {'id': 61, 'word': '买', 'pinyin': 'mǎi', 'translation_ru': 'покупать'},
    {'id': 62, 'word': '猫', 'pinyin': 'māo', 'translation_ru': 'кот; кошка'},
    {'id': 63, 'word': '没', 'pinyin': 'méi', 'translation_ru': 'нет; не (отрицание для действий в прошлом)'},
    {'id': 64, 'word': '米饭', 'pinyin': 'mǐfàn', 'translation_ru': 'варёный рис'},
    {'id': 65, 'word': '名词', 'pinyin': 'míngcí', 'translation_ru': 'существительное'},
    {'id': 66, 'word': '明天', 'pinyin': 'míngtiān', 'translation_ru': 'завтра'},
    {'id': 67, 'word': '哪', 'pinyin': 'nǎ', 'translation_ru': 'какой; который'},
    {'id': 68, 'word': '那', 'pinyin': 'nà', 'translation_ru': 'тот; то'},
    {'id': 69, 'word': '呢', 'pinyin': 'ne', 'translation_ru': 'а (вопросительное слово)'},
    {'id': 70, 'word': '你', 'pinyin': 'nǐ', 'translation_ru': 'ты; вы'},
    {'id': 71, 'word': '年', 'pinyin': 'nián', 'translation_ru': 'год'},
    {'id': 72, 'word': '女儿', 'pinyin': 'nǚ' 'ér', 'translation_ru': 'дочь'},
    {'id': 73, 'word': '朋友', 'pinyin': 'péngyou', 'translation_ru': 'друг; подруга'},
    {'id': 74, 'word': '苹果', 'pinyin': 'píngguǒ', 'translation_ru': 'яблоко'},
    {'id': 75, 'word': '七', 'pinyin': 'qī', 'translation_ru': 'семь'},
    {'id': 76, 'word': '前面', 'pinyin': 'qiánmiàn', 'translation_ru': 'спереди; впереди'},
    {'id': 77, 'word': '钱', 'pinyin': 'qián', 'translation_ru': 'деньги'},
    {'id': 78, 'word': '请', 'pinyin': 'qǐng', 'translation_ru': 'пожалуйста; просить'},
    {'id': 79, 'word': '去', 'pinyin': 'qù', 'translation_ru': 'идти; ехать'},
    {'id': 80, 'word': '热', 'pinyin': 'rè', 'translation_ru': 'жаркий; горячий'},
    {'id': 81, 'word': '人', 'pinyin': 'rén', 'translation_ru': 'человек'},
    {'id': 82, 'word': '日', 'pinyin': 'rì', 'translation_ru': 'день; солнце'},
    {'id': 83, 'word': '三', 'pinyin': 'sān', 'translation_ru': 'три'},
    {'id': 84, 'word': '商店', 'pinyin': 'shāngdiàn', 'translation_ru': 'магазин'},
    {'id': 85, 'word': '上', 'pinyin': 'shàng', 'translation_ru': 'на; вверх; прошлый'},
    {'id': 86, 'word': '上午', 'pinyin': 'shàngwǔ', 'translation_ru': 'первая половина дня; утро'},
    {'id': 87, 'word': '少', 'pinyin': 'shǎo', 'translation_ru': 'мало; немного'},
    {'id': 88, 'word': '谁', 'pinyin': 'shéi', 'translation_ru': 'кто'},
    {'id': 89, 'word': '什么', 'pinyin': 'shénme', 'translation_ru': 'что; какой'},
    {'id': 90, 'word': '十', 'pinyin': 'shí', 'translation_ru': 'десять'},
    {'id': 91, 'word': '时候', 'pinyin': 'shíhou', 'translation_ru': 'время; момент'},
    {'id': 92, 'word': '是', 'pinyin': 'shì', 'translation_ru': 'быть; есть'},
    {'id': 93, 'word': '书', 'pinyin': 'shū', 'translation_ru': 'книга'},
    {'id': 94, 'word': '水', 'pinyin': 'shuǐ', 'translation_ru': 'вода'},
    {'id': 95, 'word': '水果', 'pinyin': 'shuǐguǒ', 'translation_ru': 'фрукты'},
    {'id': 96, 'word': '睡觉', 'pinyin': 'shuìjiào', 'translation_ru': 'спать'},
    {'id': 97, 'word': '说话', 'pinyin': 'shuōhuà', 'translation_ru': 'говорить; разговаривать'},
    {'id': 98, 'word': '四', 'pinyin': 'sì', 'translation_ru': 'четыре'},
    {'id': 99, 'word': '岁', 'pinyin': 'suì', 'translation_ru': 'год (возраст)'},
    {'id': 100, 'word': '他', 'pinyin': 'tā', 'translation_ru': 'он'},
    {'id': 101, 'word': '她', 'pinyin': 'tā', 'translation_ru': 'она'},
    {'id': 102, 'word': '太', 'pinyin': 'tài', 'translation_ru': 'слишком; чрезмерно'},
    {'id': 103, 'word': '天气', 'pinyin': 'tiānqì', 'translation_ru': 'погода'},
    {'id': 104, 'word': '听', 'pinyin': 'tīng', 'translation_ru': 'слушать; слышать'},
    {'id': 105, 'word': '同学', 'pinyin': 'tóngxué', 'translation_ru': 'одногруппник; одноклассник'},
    {'id': 106, 'word': '喂', 'pinyin': 'wèi', 'translation_ru': 'алло; эй; кличка для приветствия по телефону'},
    {'id': 107, 'word': '我们', 'pinyin': 'wǒmen', 'translation_ru': 'мы'},
    {'id': 108, 'word': '喜欢', 'pinyin': 'xǐhuan', 'translation_ru': 'нравиться; любить'},
    {'id': 109, 'word': '下', 'pinyin': 'xià', 'translation_ru': 'вниз; следующий'},
    {'id': 110, 'word': '下雨', 'pinyin': 'xiàyǔ', 'translation_ru': 'идёт дождь'},
    {'id': 111, 'word': '先生', 'pinyin': 'xiānsheng', 'translation_ru': 'господин; мистер; муж'},
    {'id': 112, 'word': '喜欢', 'pinyin': 'xǐhuan', 'translation_ru': 'любить; нравиться'},
    {'id': 113, 'word': '小', 'pinyin': 'xiǎo', 'translation_ru': 'маленький'},
    {'id': 114, 'word': '小姐', 'pinyin': 'xiǎojiě', 'translation_ru': 'мисс; молодая женщина'},
    {'id': 115, 'word': '写', 'pinyin': 'xiě', 'translation_ru': 'писать'},
    {'id': 116, 'word': '些', 'pinyin': 'xiē', 'translation_ru': 'немного; несколько'},
    {'id': 117, 'word': '谢谢', 'pinyin': 'xièxie', 'translation_ru': 'спасибо'},
    {'id': 118, 'word': '星期', 'pinyin': 'xīngqī', 'translation_ru': 'неделя'},
    {'id': 119, 'word': '学生', 'pinyin': 'xuésheng', 'translation_ru': 'студент; ученик'},
    {'id': 120, 'word': '学习', 'pinyin': 'xuéxí', 'translation_ru': 'изучать; учиться'},
    {'id': 121, 'word': '学校', 'pinyin': 'xuéxiào', 'translation_ru': 'школа'},
    {'id': 122, 'word': '雪', 'pinyin': 'xuě', 'translation_ru': 'снег'},
    {'id': 123, 'word': '一', 'pinyin': 'yī', 'translation_ru': 'один'},
    {'id': 124, 'word': '医生', 'pinyin': 'yīshēng', 'translation_ru': 'врач'},
    {'id': 125, 'word': '医院', 'pinyin': 'yīyuàn', 'translation_ru': 'больница'},
    {'id': 126, 'word': '椅子', 'pinyin': 'yǐzi', 'translation_ru': 'стул'},
    {'id': 127, 'word': '有', 'pinyin': 'yǒu', 'translation_ru': 'иметь; иметься'},
    {'id': 128, 'word': '月', 'pinyin': 'yuè', 'translation_ru': 'месяц; луна'},
    {'id': 129, 'word': '再见', 'pinyin': 'zàijiàn', 'translation_ru': 'до свидания; пока'},
    {'id': 130, 'word': '怎麼', 'pinyin': 'zěnme', 'translation_ru': 'как? каким образом?'},
    {'id': 131, 'word': '怎么', 'pinyin': 'zěnme', 'translation_ru': 'как? каким образом?'},
    {'id': 132, 'word': '这', 'pinyin': 'zhè', 'translation_ru': 'это'},
    {'id': 133, 'word': '中国', 'pinyin': 'Zhōngguó', 'translation_ru': 'Китай'},
    {'id': 134, 'word': '中午', 'pinyin': 'zhōngwǔ', 'translation_ru': 'полдень'},
    {'id': 135, 'word': '住', 'pinyin': 'zhù', 'translation_ru': 'жить; останавливаться'},
    {'id': 136, 'word': '桌子', 'pinyin': 'zhuōzi', 'translation_ru': 'стол'},
    {'id': 137, 'word': '字', 'pinyin': 'zì', 'translation_ru': 'иероглиф; символ'},
    {'id': 138, 'word': '走', 'pinyin': 'zǒu', 'translation_ru': 'идти; уходить'},
    {'id': 139, 'word': '左边', 'pinyin': 'zuǒbian', 'translation_ru': 'слева'},
    {'id': 140, 'word': '坐', 'pinyin': 'zuò', 'translation_ru': 'сидеть; ехать (на транспорте)'},
    {'id': 141, 'word': '做', 'pinyin': 'zuò', 'translation_ru': 'делать; выполнять'},
]
SENTENCES = [
    {"id": 1, "sentence": "我是学生。", "pinyin": "Wǒ shì xuéshēng.", "translation_ru": "Я студент."},
    {"id": 2, "sentence": "他是老师。", "pinyin": "Tā shì lǎoshī.", "translation_ru": "Он учитель."},
    {"id": 3, "sentence": "我喜欢中国。", "pinyin": "Wǒ xǐhuan Zhōngguó.", "translation_ru": "Мне нравится Китай."},
    {"id": 4, "sentence": "我们学习汉语。", "pinyin": "Wǒmen xuéxí Hànyǔ.",
     "translation_ru": "Мы изучаем китайский язык."},
    {"id": 5, "sentence": "今天很热。", "pinyin": "Jīntiān hěn rè.", "translation_ru": "Сегодня очень жарко."},

    {"id": 6, "sentence": "你叫什么名字？", "pinyin": "Nǐ jiào shénme míngzi?", "translation_ru": "Как тебя зовут?"},
    {"id": 7, "sentence": "我叫李明。", "pinyin": "Wǒ jiào Lǐ Míng.", "translation_ru": "Меня зовут Ли Мин."},
    {"id": 8, "sentence": "他有很多书。", "pinyin": "Tā yǒu hěn duō shū.", "translation_ru": "У него много книг."},
    {"id": 9, "sentence": "这是什么？", "pinyin": "Zhè shì shénme?", "translation_ru": "Что это?"},
    {"id": 10, "sentence": "那不是我的。", "pinyin": "Nà bú shì wǒ de.", "translation_ru": "То не моё."},

    {"id": 11, "sentence": "我在家。", "pinyin": "Wǒ zài jiā.", "translation_ru": "Я дома."},
    {"id": 12, "sentence": "她在办公室。", "pinyin": "Tā zài bàngōngshì.", "translation_ru": "Она в офисе."},
    {"id": 13, "sentence": "我们一起去。", "pinyin": "Wǒmen yìqǐ qù.", "translation_ru": "Мы идём вместе."},
    {"id": 14, "sentence": "他每天跑步。", "pinyin": "Tā měitiān pǎobù.", "translation_ru": "Он бегает каждый день."},
    {"id": 15, "sentence": "我会说一点中文。", "pinyin": "Wǒ huì shuō yìdiǎn Zhōngwén.",
     "translation_ru": "Я могу немного говорить по-китайски."},

    {"id": 16, "sentence": "请给我菜单。", "pinyin": "Qǐng gěi wǒ càidān.",
     "translation_ru": "Пожалуйста, дайте мне меню."},
    {"id": 17, "sentence": "我想买这个。", "pinyin": "Wǒ xiǎng mǎi zhège.", "translation_ru": "Я хочу купить это."},
    {"id": 18, "sentence": "太贵了。", "pinyin": "Tài guì le.", "translation_ru": "Слишком дорого."},
    {"id": 19, "sentence": "我在等朋友。", "pinyin": "Wǒ zài děng péngyǒu.", "translation_ru": "Я жду друга."},
    {"id": 20, "sentence": "你去哪儿？", "pinyin": "Nǐ qù nǎr?", "translation_ru": "Куда ты идёшь?"},

    {"id": 21, "sentence": "他是我的哥哥。", "pinyin": "Tā shì wǒ de gēge.", "translation_ru": "Он мой старший брат."},
    {"id": 22, "sentence": "请慢一点说。", "pinyin": "Qǐng màn yìdiǎn shuō.",
     "translation_ru": "Пожалуйста, говорите помедленнее."},
    {"id": 23, "sentence": "我不懂。", "pinyin": "Wǒ bù dǒng.", "translation_ru": "Я не понимаю."},
    {"id": 24, "sentence": "可以再说一遍吗？", "pinyin": "Kěyǐ zài shuō yí biàn ma?",
     "translation_ru": "Можете повторить ещё раз?"},
    {"id": 25, "sentence": "今天天气很好。", "pinyin": "Jīntiān tiānqì hěn hǎo.",
     "translation_ru": "Сегодня хорошая погода."},

    {"id": 26, "sentence": "外面很冷。", "pinyin": "Wàimiàn hěn lěng.", "translation_ru": "На улице холодно."},
    {"id": 27, "sentence": "我喜欢吃苹果。", "pinyin": "Wǒ xǐhuan chī píngguǒ.",
     "translation_ru": "Мне нравится есть яблоки."},
    {"id": 28, "sentence": "你会开车吗？", "pinyin": "Nǐ huì kāichē ma?", "translation_ru": "Ты умеешь водить?"},
    {"id": 29, "sentence": "医生在医院。", "pinyin": "Yīshēng zài yīyuàn.", "translation_ru": "Врач в больнице."},
    {"id": 30, "sentence": "请坐。", "pinyin": "Qǐng zuò.", "translation_ru": "Садитесь, пожалуйста."},
    {"id": 31, "sentence": "我有一个朋友。", "pinyin": "Wǒ yǒu yí gè péngyǒu.",
     "translation_ru": "У меня есть один друг."},
    {"id": 32, "sentence": "她是我的妈妈。", "pinyin": "Tā shì wǒ de māma.", "translation_ru": "Она моя мама."},
    {"id": 33, "sentence": "这是我的书。", "pinyin": "Zhè shì wǒ de shū.", "translation_ru": "Это моя книга."},
    {"id": 34, "sentence": "那是你的包吗？", "pinyin": "Nà shì nǐ de bāo ma?", "translation_ru": "Это твоя сумка?"},
    {"id": 35, "sentence": "我在学校。", "pinyin": "Wǒ zài xuéxiào.", "translation_ru": "Я в школе."},

    {"id": 36, "sentence": "他在中国工作。", "pinyin": "Tā zài Zhōngguó gōngzuò.",
     "translation_ru": "Он работает в Китае."},
    {"id": 37, "sentence": "我们有两个老师。", "pinyin": "Wǒmen yǒu liǎng gè lǎoshī.",
     "translation_ru": "У нас есть два учителя."},
    {"id": 38, "sentence": "我喜欢喝水。", "pinyin": "Wǒ xǐhuan hē shuǐ.", "translation_ru": "Мне нравится пить воду."},
    {"id": 39, "sentence": "你喜欢他吗？", "pinyin": "Nǐ xǐhuan tā ma?", "translation_ru": "Он тебе нравится?"},
    {"id": 40, "sentence": "我很忙。", "pinyin": "Wǒ hěn máng.", "translation_ru": "Я очень занят."},

    {"id": 41, "sentence": "今天我不忙。", "pinyin": "Jīntiān wǒ bù máng.", "translation_ru": "Сегодня я не занят."},
    {"id": 42, "sentence": "他会说汉语。", "pinyin": "Tā huì shuō Hànyǔ.",
     "translation_ru": "Он умеет говорить по-китайски."},
    {"id": 43, "sentence": "我不会写汉字。", "pinyin": "Wǒ bú huì xiě Hànzì.",
     "translation_ru": "Я не умею писать иероглифы."},
    {"id": 44, "sentence": "我们去学校。", "pinyin": "Wǒmen qù xuéxiào.", "translation_ru": "Мы идём в школу."},
    {"id": 45, "sentence": "他来中国了。", "pinyin": "Tā lái Zhōngguó le.", "translation_ru": "Он приехал в Китай."},

    {"id": 46, "sentence": "我想喝咖啡。", "pinyin": "Wǒ xiǎng hē kāfēi.", "translation_ru": "Я хочу выпить кофе."},
    {"id": 47, "sentence": "你想吃什么？", "pinyin": "Nǐ xiǎng chī shénme?", "translation_ru": "Что ты хочешь поесть?"},
    {"id": 48, "sentence": "这儿有饭店。", "pinyin": "Zhèr yǒu fàndiàn.", "translation_ru": "Здесь есть ресторан."},
    {"id": 49, "sentence": "我认识他。", "pinyin": "Wǒ rènshi tā.", "translation_ru": "Я его знаю."},
    {"id": 50, "sentence": "我们都是学生。", "pinyin": "Wǒmen dōu shì xuéshēng.", "translation_ru": "Мы все студенты."}
]
